In [1]:
import numpy as np
np.random.seed(696969696969696969696969)

import requests
import json
# r = requests.get("https://api.opendota.com/api/players/91886888/matches?region=2&limit=5")
# with open('matches_sri_5.json', 'w') as data_file:
#     json.dump(r.json(),data_file)

In [2]:
# import bigjson

# with open('E:\yasp-dump.json\yasp-dump.json', 'rb') as f:
#     j = bigjson.load(f)
#     element = j[4]
#     print(element)

# import ijson

# with open('E:\yasp-dump.json\yasp-dump.json', 'rb') as input_file:
#         # load json iteratively
#         parser = ijson.parse(input_file)
#         chat = ijson.items(input_file, 'features.item.chat.item')
#         for item in chat:
#             print('Chat: {}'.format(item))
# #         for prefix, event, value in parser:
# #             print('prefix={}, event={}, value={}'.format(prefix, event, value))

# import ijson
# f = open('E:\yasp-dump.json\yasp-dump.json', 'r')
# line = f.read(300000)
# print(line)

In [3]:
wins = {}
losses = {}
both = {}
def remove_non_ascii(text):
    return ''.join(i for i in text if ord(i)<128)

for i in range(1,11):
    filename = 'games100-' + str(i) + '.json'
    with open(filename, 'r', encoding="utf-8") as data_file:
        data = json.load(data_file)
        counter = 0

        for element in data:
            counter = counter+1
#             print(counter)
#             print(element)
            element['match_id'] = str(element['match_id']).replace('[', '').replace(']', '')
            element['radiant_win'] = str(element['radiant_win']).replace('[', '').replace(']', '')
    #         r = requests.get("https://api.opendota.com/api/matches/" + str(element['match_id']))
    #         r = r.json()
            r = element
#             print(r)

            r.pop('all_word_counts', None)
    #         r.pop('match_id', None)
            r.pop('barracks_status_dire', None)
            r.pop('barracks_status_radiant', None)
    #         r.pop('chat', None)
            r.pop('cluster', None)
            r.pop('cosmetics', None)
            r.pop('dire_score', None)
            r.pop('dire_team_id', None)
            r.pop('draft_timings', None)
            r.pop('duration', None)
            r.pop('engine', None)
    #         r.pop('first_blood_time', None)
    #         r.pop('game_mode', None)
            r.pop('human_players', None)
            r.pop('leagueid', None)
            r.pop('lobby_type', None)
            r.pop('match_seq_num', None)
            r.pop('negative_votes', None)
            r.pop('objectives', None)
            r.pop('picks_bans', None)
            r.pop('positive_votes', None)
            r.pop('radiant_gold_adv', None)
            r.pop('radiant_score', None)
            r.pop('radiant_team_id', None)
    #         r.pop('radiant_win', None)
            r.pop('radiant_xp_adv', None)
            r.pop('skill', None)
            r.pop('start_time', None)
            r.pop('teamfights', None)
            r.pop('tower_status_dire', None)
            r.pop('tower_status_radiant', None)
            r.pop('version', None)
            r.pop('replay_salt', None)
            r.pop('series_id', None)
            r.pop('series_type', None)
            r.pop('players', None)
            r.pop('patch', None)
            r.pop('region', None)
            r.pop('throw', None)
            r.pop('loss', None)
            r.pop('win', None)
            r.pop('my_word_counts', None)
            r.pop('comeback', None)
            r.pop('stomp', None)
            r.pop('replay_url', None)

#             print(r)
            pop_chat = []
            for index, item in enumerate(r['chat']):
                if item['slot'] == 10:
                    pop_chat.append(index)

#             print("pop index" + str(pop_chat))
#             for item in reversed(pop_chat):
#                 print("Popped" + str(r['chat'].pop(int(item))))

            with open('chat_wheel.json', 'r',encoding='utf8') as data_file:
                chat_wheel = json.load(data_file)
            
            for index, item in enumerate(r['chat']):
                if item['type'] == 'chat':
#                     item['key'] = ''.join(filter(lambda x: x in printable, item['key']))
                    remove_non_ascii(item['key'])

            for idx, item in enumerate(r['chat']):
                if item['type'] == 'chatwheel':
    #                 print(item['key'])
                    item['type'] = 'chat'
                    item['key'] = chat_wheel[item['key']].get('message')

            both[element['match_id']] = r
#             print("Added to both.")
#             print(r)

            if r['radiant_win'] == str('True'):
                wins[element['match_id']] = r
#                 print("Added to wins.")
            else:
                losses[element['match_id']] = r
#                 print("Added to losses.")
                
    data_file.close()
    
# with open('wins.json', 'w') as outfile:
#     json.dump(wins, outfile)
#     outfile.close()
# with open('losses.json', 'w') as outfile:
#     json.dump(losses, outfile)
#     outfile.close()
# with open('both.json', 'w') as outfile:
#     json.dump(both, outfile)
#     outfile.close()

    # print("Wins:")
    # print(wins)
    # print("Losses:")
    # print(losses)
    # print("Both:")
    # print(both)


In [4]:
# wins

In [5]:
import copy
win_chats={}
lose_chats={}
for game in wins:
    game_copy = copy.deepcopy(wins[game])
    game_copy['chat']=[line for line in wins[game]['chat'] if not (line['slot']>4)]
    #print(game_copy)
    win_chats[game]=game_copy
    
    game_copy = copy.deepcopy(wins[game])
    game_copy['chat']=[line for line in wins[game]['chat'] if not (line['slot']<=4)]
    #print(game_copy)
    lose_chats[game]=game_copy

for game in losses:
    game_copy = copy.deepcopy(losses[game])
    game_copy['chat']=[line for line in losses[game]['chat'] if not (line['slot']>4)]
    lose_chats[game]=game_copy
    
    game_copy = copy.deepcopy(losses[game])
    game_copy['chat']=[line for line in losses[game]['chat'] if not (line['slot']<=4)]
    #print(game_copy)
    win_chats[game]=game_copy

# print(win_chats) 
# print(len(win_chats))
# print(lose_chats) 
# len(lose_chats)


In [6]:
wordDict = {}
for game in both.keys():
    for i in both[game]['chat']:
        if i['key'] is not None:
            for word in i['key'].split():
                if word in wordDict:
                    wordDict[word] = wordDict[word]+1
                else:
                    wordDict[word]=1
        

In [7]:
# print(len(both.keys()))
# for i in both.keys():
#     print(i)

In [8]:
# wordDict

In [9]:
import operator
wordDictCounts = sorted(wordDict.items(), key=operator.itemgetter(1))

In [10]:
# wordDictCounts[::-1]

In [11]:
words = list(wordDict.keys())

In [12]:
# words

In [13]:
words.insert(0,'Radiant Wins')

In [14]:
import numpy as np
AllWords = np.zeros((len(both)*2,len(wordDict)+1), dtype=int)
game_index = 0
for game in win_chats.keys():
    AllWords[game_index][0]=1
    for line in win_chats[game]['chat']:
        if line['key'] is not None:
            for word in line['key'].split():
                AllWords[game_index][words.index(word)]=AllWords[game_index][words.index(word)]+1
    game_index+=1
for game in lose_chats.keys():
    for line in lose_chats[game]['chat']:
        if line['key'] is not None:
            for word in line['key'].split():
                AllWords[game_index][words.index(word)]=AllWords[game_index][words.index(word)]+1
    game_index+=1

In [15]:
# AllWords

In [16]:
import pandas as pd 
df = pd.DataFrame(AllWords, columns = words) 

In [17]:
# df

In [18]:
X = df.iloc[:,1:].values
y = df.iloc[:,0].values

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [20]:
# y_test

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(copy=False)
# StandardScaler(copy=False,with_mean=False).fit(X_train)
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [23]:
y_pred = classifier.predict(X_test)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[120  96]
 [105 111]]
              precision    recall  f1-score   support

           0       0.53      0.56      0.54       216
           1       0.54      0.51      0.52       216

    accuracy                           0.53       432
   macro avg       0.53      0.53      0.53       432
weighted avg       0.53      0.53      0.53       432



In [25]:
error = []

# Calculating error for K values between 1 and 40
for i in range(1, 40):
    print(i)
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))
plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')

In [27]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB(priors = [.5,.5])

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [28]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5


In [29]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

tree.plot_tree(clf)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [30]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5578703703703703


In [34]:
from sklearn.model_selection import KFold, cross_val_score
k_fold = KFold(n_splits=3, shuffle=True, random_state=0)
clf = DecisionTreeClassifier()
print(cross_val_score(clf, X_train, y_train, cv=k_fold, n_jobs=1))

[0.515625   0.55555556 0.53472222]


In [31]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

tree.plot_tree(clf)

y_pred=clf.predict(X_test)

In [32]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5694444444444444


In [33]:
from sklearn.model_selection import KFold, cross_val_score
k_fold = KFold(n_splits=3, shuffle=True, random_state=0)
clf = RandomForestClassifier(n_estimators=100)
print(cross_val_score(clf, X, y, cv=k_fold, n_jobs=1))

[0.56805556 0.60555556 0.59027778]


In [ ]:
from sklearn.model_selection import KFold, cross_val_score
Forest_numbers={}
for k in range(51,151,10):
    k_fold = KFold(n_splits=11, shuffle=True, random_state=0)
    clf = RandomForestClassifier(n_estimators=k)
    Forest_numbers[k] = cross_val_score(clf, X, y, cv=k_fold, n_jobs=1)